version: '3.7'

services:
  aut_os_mainnet:
    container_name: aut_os_mainnet
    image: autlabs/aut-os:mainnet
    ports:
      - '4002:80'

  aut_os_main:
    container_name: aut_os_main
    image: autlabs/aut-os:main
    ports:
      - '4001:80'
