version: '3.7'

services:
  my_aut_id_dev:
    container_name: my_aut_id_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4001:80'