name: Deployment Prod

on:
  push:
    branches:
      - mainnet

jobs:
  build-and-deploy:
    name: Build and Deployment
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      # Deploy to Server
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            #!/usr/bin/env bash

            cd aut-id
            sudo git checkout mainnet;
            sudo git pull origin mainnet;

            echo "Stopping and removing specific service: aut_os_mainnet"
            sudo docker-compose stop aut_os_mainnet
            sudo docker-compose rm -f aut_os_mainnet

            echo "Removing dangling images"
            sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true

            sudo docker build -t autlabs/aut-os:mainnet . --build-arg ENV_FILE=.env_prod
            # sudo docker push autlabs/aut-os:mainnet

            echo "Pulling the new image"
            # sudo docker-compose pull aut_os_mainnet
            docker-compose up -d --build aut_os_mainnet --remove-orphans

            exit 0;