name: Deployment Dev

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deployment
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      # Deploy to Server
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TESTNET_FRONTEND_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.FRONTEND_SSH_KEY }}
          script: |
            #!/usr/bin/env bash

            cd aut-os
            sudo git checkout main;
            sudo git pull origin main;

            sudo docker build -t autlabs/aut-os:main . --build-arg ENV_FILE=.env
            # sudo docker push autlabs/aut-os:main

            echo "Stopping and removing specific service: aut_os_main"
            sudo docker-compose stop aut_os_main
            sudo docker-compose rm -f aut_os_main

            echo "Removing dangling images"
            sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true

            echo "Pulling the new image"
            # sudo docker-compose pull aut_os_main
            docker-compose up -d --build aut_os_main

            exit 0;